export const ONBOARDING_MANAGER_INTERNAL_COMMANDS_QUEUE_NAME =
  'ONBOARDING_MANAGER_INTERNAL_COMMANDS_QUEUE_NAME';

export const COMPANY_REGISTRY_PUBLIC_COMMANDS_QUEUE_NAME =
  'COMPANY_REGISTRY_PUBLIC_COMMANDS_QUEUE_NAME';

export const ACCOUNT_REGISTRY_PUBLIC_COMMANDS_QUEUE_NAME =
  'ACCOUNT_REGISTRY_PUBLIC_COMMANDS_QUEUE_NAME';
